baseURL = "https://ofilibre.urjc.es"
languageCode = "es-es"
title = "OfiLibre URJC"
theme = ["navigator-hugo", "decap-cms"]
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = false
dateFormat = "2 January 2006"
summaryLength = 10
enableRobotsTXT = true
enableGitInfo = false
pygmentsCodeFences = true
googleAnalytics = ""

author = "OfiLibre URJC"
description = "Oficina de Conocimiento y Cultura Libres de la Universidad Rey Juan Carlos: ayudamos a la comunidad universitaria a comprender y aplicar la cultura libre, la publicación en abierto, los datos abiertos y el software libre."

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "JSON", "RSS"]

[params]
rawBase = "https://raw.githubusercontent.com/EAA-URJC/eaa-urjc.github.io/refs/heads/main"
contacto_form_action = "sendmail.php"

[subscription]
enable = true
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"

[params.preloader]
enable = false
preloader = "images/preloader/preloader.gif"

# cookies
[params.cookies]
enable = false
expire_days = 1

# Allow HTML in Markdown pages
[markup.goldmark.renderer]
unsafe = true
