backend:
  name: turbo-github
  turbo_site_id: f5c8ad16-8cbe-49f9-b2aa-f4f4abd765ef
locale: es
media_folder: static
public_folder: /
collections:
  - name: 'navigation'
    label: 'Menús'
    files:
      - file: 'config/_default/menus.yml'
        name: 'menus'
        label: 'Menús'
        fields:
          - widget: list
            name: nav
            label: Elementos del menú
            required: true
            hint: '↑ Aparecen en la cabecera de la web'
            fields:
              - { label: 'Anidar de', name: 'parent', widget: string, required: false, hint: 'Campo "nombre" del elemento del que anidará' }
              - { label: 'Nombre', name: 'name', widget: string, required: true }
              - { label: 'Dirección URL', name: 'url', widget: string, required: true }
              - { label: 'Prioridad', name: 'weight', widget: number, value_type: int, required: true, min: 1, hint: 'Menor valor es mayor prioridad' }
          - widget: list
            name: service
            label: Servicios
            required: true
            hint: '↑ Aparecen en el faldón de la web'
            fields:
              - { label: 'Nombre', name: 'name', widget: string, required: true }
              - { label: 'Dirección URL', name: 'url', widget: string, required: true }
              - { label: 'Prioridad', name: 'weight', widget: number, value_type: int, required: true, min: 1, hint: 'Menor valor es mayor prioridad' }
          - widget: list
            name: quicklink
            label: Enlaces rápidos
            required: true
            hint: '↑ Aparecen en el faldón de la web'
            fields:
              - { label: 'Nombre', name: 'name', widget: string, required: true }
              - { label: 'Dirección URL', name: 'url', widget: string, required: true }
              - { label: 'Prioridad', name: 'weight', widget: number, value_type: int, required: true, min: 1, hint: 'Menor valor es mayor prioridad' }
  - label: 'Blog'
    name: 'blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    media_folder: '/../../../static/blog/{{slug}}'
    public_folder: '/blog/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime', date_format: 'YYYY-MM-DD' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Categorías', name: 'categories', widget: 'hidden', default: ["Universidad"]}
      - { label: 'Etiquetas', name: 'tags', widget: 'list'}
      - { label: 'Logo', name: 'image', widget: 'image', default: '/logos/logo-ofilibre-2025.jpg'}
      - { label: 'Cuerpo', name: 'body', widget: 'richtext' }

  - label: 'Editorial'
    name: 'editorial'
    folder: 'content/editorial'
    create: true
    slug: '{{slug}}'
    media_folder: '/../../../static/editorial/{{slug}}'
    public_folder: '/editorial/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Cuerpo', name: 'body', widget: 'richtext' }
