backend:
  name: turbo-github
  turbo_site_id: f5c8ad16-8cbe-49f9-b2aa-f4f4abd765ef
locale: es
media_folder: static
public_folder: /
collections:
  - name: 'navigation'
    label: 'Menús'
    files:
      - file: 'config/_default/params.yml'
        name: 'params'
        label: 'Configuración'
        fields:
          - { widget: string, name: 'home', label: 'Título enlace portada' }
          - { widget: boolean, name: 'menufixed', label: 'Fijar el menú' }
          - { widget: string, name: 'footerBlogTitle', label: 'Título blog faldón' }
          - { widget: string, name: 'footerServiceTitle', label: 'Título servicios faldón' }
          - { widget: string, name: 'footerQuicklinkTitle', label: 'Título enlaces rápidos faldón' }
          - widget: object
            name: 'hero'
            label: 'Destacado (módulo)'
            fields:
              - { widget: boolean, name: 'enable', label: 'Activado' }
              - { widget: string, name: 'heading', label: 'Titular' }
              - { widget: text, name: 'description', label: 'Descripción' }
              - { widget: boolean, name: 'button', label: 'Botón' }
              - { widget: string, name: 'btnText', label: 'Texto del botón' }
              - { widget: string, name: 'btnURL', label: 'URL del botón' }
              - { widget: string, name: 'videoURL', label: 'URL del vídeo' }
          - widget: object
            name: 'blog'
            label: 'Blog (módulo)'
            fields:
              - { widget: boolean, name: 'enable', label: 'Activado' }
              - { widget: string, name: 'topTitle', label: 'Sobretítulo' }
              - { widget: string, name: 'title', label: 'Título' }
          - widget: object
            name: 'contacto'
            label: 'Contacto (módulo)'
            fields:
              - { widget: boolean, name: 'enable', label: 'Activado' }
              - { widget: string, name: 'topTitle', label: 'Sobretítulo' }
              - { widget: string, name: 'title', label: 'Título' }
              - { widget: text, name: 'subtitle', label: 'Subtítulo' }
              - { widget: text, name: 'address', label: 'Dirección' }
              - { widget: string, name: 'email', label: 'Correo-e' }
              - { widget: string, name: 'x', label: 'URL al perfil de X', required: false }
              - { widget: string, name: 'mastodon', label: 'URL al perfil de Mastodon', required: false }
              - { widget: string, name: 'telegram', label: 'URL al perfil de Telegram', required: false }
              - { widget: string, name: 'instagram', label: 'URL al perfil de Instagram', required: false }
              - { widget: string, name: 'gitlab', label: 'URL al perfil de GitLab.com', required: false }
              - { widget: hidden, name: 'rss', label: 'URL a la fuente de noticias', default: /index.xml }
              - { widget: number, value_type: float, name: 'mapLatitude', label: 'Latitud' }
              - { widget: number, value_type: float, name: 'mapLongitude', label: 'Longitud' }
              - { widget: hidden, name: 'mapMarker', label: 'Marcador del mapa', default: '/contact/marker.png' }

      - file: 'config/_default/menus.yml'
        name: 'menus'
        label: 'Menús'
        fields:
          - widget: list
            name: nav
            label: Elementos del menú
            required: true
            hint: '↑ Aparecen en la cabecera de la web'
            fields:
              - { label: 'Anidar de', name: 'parent', widget: string, required: false, hint: 'Campo "nombre" del elemento del que anidará' }
              - { label: 'Nombre', name: 'name', widget: string, required: true }
              - { label: 'Dirección URL', name: 'url', widget: string, required: true }
              - { label: 'Prioridad', name: 'weight', widget: number, value_type: int, required: true, min: 1, hint: 'Menor valor es mayor prioridad' }
          - widget: list
            name: service
            label: Servicios
            required: true
            hint: '↑ Aparecen en el faldón de la web'
            fields:
              - { label: 'Nombre', name: 'name', widget: string, required: true }
              - { label: 'Dirección URL', name: 'url', widget: string, required: true }
              - { label: 'Prioridad', name: 'weight', widget: number, value_type: int, required: true, min: 1, hint: 'Menor valor es mayor prioridad' }
          - widget: list
            name: quicklink
            label: Enlaces rápidos
            required: true
            hint: '↑ Aparecen en el faldón de la web'
            fields:
              - { label: 'Nombre', name: 'name', widget: string, required: true }
              - { label: 'Dirección URL', name: 'url', widget: string, required: true }
              - { label: 'Prioridad', name: 'weight', widget: number, value_type: int, required: true, min: 1, hint: 'Menor valor es mayor prioridad' }

      - file: 'data/es/carrusel.yml'
        name: 'carrusel'
        label: 'Carrusel'
        fields:
          - { widget: boolean, label: 'Activado', name: 'enable' }
          - { widget: string, label: 'Sobretítulo', name: 'topTitle' }
          - { widget: string, label: 'Título', name: 'title' }
          - widget: list
            name: 'item'
            label: 'Elementos'
            fields:
              - { widget: string, label: 'Icono', name: 'icon', hint: 'fas + nombre del icono de Font Awesome. Lista: https://fontawesome.com/search?ic=free-collection' }
              - { widget: string, label: 'Título', name: 'title' }
              - { widget: string, label: 'Enlace', name: 'link' }
              - { widget: richtext, label: 'Descripción', name: 'description' }

      - file: 'data/es/recursos.yml'
        name: 'recursos'
        label: 'Recursos'
        fields:
          - { widget: boolean, label: 'Activado', name: 'enable' }
          - { widget: string, label: 'Sobretítulo', name: 'topTitle' }
          - { widget: string, label: 'Título', name: 'title' }
          - widget: list
            name: 'item'
            label: 'Elementos'
            fields:
              - { widget: string, label: 'Icono', name: 'icon', hint: 'fas + nombre del icono de Font Awesome. Lista: https://fontawesome.com/search?ic=free-collection' }
              - { widget: string, label: 'Título', name: 'title' }
              - { widget: string, label: 'Enlace', name: 'link' }
              - { widget: richtext, label: 'Descripción', name: 'description' }

  - label: 'Blog'
    name: 'blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    media_folder: '/../../../static/blog/{{slug}}'
    public_folder: '/blog/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime', date_format: 'YYYY-MM-DD' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - { label: 'Categorías', name: 'categories', widget: 'hidden', default: ["Universidad"]}
      - { label: 'Etiquetas', name: 'tags', widget: 'list'}
      - { label: 'Logo', name: 'image', widget: 'image', default: '/logos/logo-ofilibre-2025.jpg'}
      - { label: 'Cuerpo', name: 'body', widget: 'richtext' }

  - label: 'Editorial'
    name: 'editorial'
    folder: 'content/editorial'
    create: true
    slug: '{{slug}}'
    media_folder: '/../../../static/editorial/{{slug}}'
    public_folder: '/editorial/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Cuerpo', name: 'body', widget: 'richtext' }
